### PR TITLE
Fix MOD20 VM ARM template - fixes #51

### LINKED ISSUE #51: MOD20: ARM template for deploying VMs fails/is invalid
Hi There,

I've been trying to install the VMs using the ARM template in preparation to run these sessions, but am getting an error in the ARM template:
image

The ARM template is: https://github.com/microsoft/ignite-learning-paths-training-mod/blob/master/mod20/DeploymentTemplates/azuredeploy-vms.json

I've tried putting the content of the template into a deployment manually and an error parsing the template is reported:
image

It looks like this resource is causing the problem:
https://github.com/microsoft/ignite-learning-paths-training-mod/blob/master/mod20/DeploymentTemplates/azuredeploy-vms.json#L407

Any help is appreciated.

### PR DESCRIPTION
**Pull request by PlagueHO**
This PR fixes an invalid character in the ARM template for deploying the VMs for MOD20. It also cleans up some trailing whitespace issues (thanks to the awesome VS Code).

---
This change is [Reviewable](https://reviewable.io/reviews/microsoft/ignite-learning-paths-training-mod/52)

### CODE REVIEW

**Comment by PlagueHO** [comment]
Please hold review/merge of this PR for now as I want to run some more testing on it.

**Comment by PlagueHO** [comment]
I found that the sudo in the `commandToExecute` actually causes the extension provisioning to fail due to an error 127. Removing the sudo prevents the error from occurring.

**Comment by FBoucher** [comment]
Thank you @PlagueHO. Because the only things that left now are some extra spaces and honestly, I think they are fine there, we won't merge this PR.

**Comment by PlagueHO** [comment]
Thanks @FBoucher ! I'm running three of these sessions next week so this will help :grin:

**Pull request merged**
